config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :tasks
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, :presence => true
  validates :description, :presence => true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true

  def self.done
    return Task.all.where(:done => true).sort_by{|object| object.description.downcase}
  end

  def self.notDone
    return Task.all.where(:done => false).sort_by{|object| object.description.downcase} 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all.sort_by{|object| object.name.downcase}
    render :index
  end

  def show
    @list = List.find(params[:id])
    @doneTasks = @list.tasks.where(:done => true).sort_by{|object| object.description.downcase}
    @notDoneTasks = @list.tasks.where(:done => false).sort_by{|object| object.description.downcase}
    render :show
  end

  def new
    @list = List.new()
    render :new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to  lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
    render :edit
  end

  def update
    @list= List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.tasks.each do |task|
      task.destroy
    end
    @list.destroy
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name, :description)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new()
    render :new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      flash[:notice] = "Task successfully added!"
      redirect_to  list_path(@task.list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    render :edit
  end

  def update
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to list_path(@task.list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    @task.destroy
    redirect_to lists_path
  end

  private
  def task_params
    params.require(:task).permit(:description, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<div class="well col-sm-6">
  <%= form_for @list do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <%= f.submit :class => 'btn btn-warning'%>
  <% end %>
  <br />
  <p><%= link_to "Return to lists", lists_path, :class => 'btn btn-info'%></p>
</div>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Lists</h1>
  </div>
</div>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<h3>Finished Tasks</h3>
<ul>
<% Task.done.each do |task| %>
<li><%= task.description %></li>
<% end %>
</ul>

<h3>Unfinished Tasks</h3>
<ul>
<% Task.notDone.each do |task| %>
<li><%= task.description %></li>
<% end %>
</ul>

<p><%= link_to "Add a list", new_list_path %></p>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<% content_for(:title, "List | To Do") %>

<h1><%= @list.name %></h1>

<% if @list.tasks.any? %>
  <div class="col-sm-6">
    <h3>Not done tasks:</h3>
    <ul>
      <% @notDoneTasks.each do |task| %>
        <li>
          <h3><%= task.description %></h3>
          <%= link_to "Edit", edit_list_task_path(@list, task) %> |
          <%= link_to "Delete", list_task_path(@list, task),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
        </li>
        <br />
      <% end %>
    </ul>
  </div>
  <div class="col-sm-6">
    <h3>Done tasks:</h3>
    <ul>
      <% @doneTasks.each do |task| %>
        <li>
          <h3><%= task.description %></h3>
          <%= link_to "Edit", edit_list_task_path(@list, task) %> |
          <%= link_to "Delete", list_task_path(@list, task),
                                   :data => {:confirm => "Are you sure?",
                                                  :method => "delete"} %>
        </li>
        <br />
      <% end %>
    </ul>
  </div>
<% else %>
  <p>There are no tasks yet!</p>
<% end %>

<p><%= link_to "Add a task", new_list_task_path(@list), :class => 'btn btn-warning' %></p>
<p><%= link_to "Edit List", edit_list_path(@list), :class => 'btn btn-success' %></p>
<p><%= link_to "Delete List", list_path(@list),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"}, :class => 'btn btn-danger' %></p>

<p><%= link_to "Return to lists", lists_path, :class => 'btn btn-info' %></p>

app/views/tasks/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<div class="well">
<%= form_for [@list, @task], :html => { :class => "form-horizontal" } do |f| %>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>
<div class="form-group">
  <%= f.label 'Done?' %>
  <%= f.select :done, options_for_select([["This task is NOT done", false], ["This task is done", true]], @task.done) %>
</div>
  <%= f.submit :class => 'btn btn-warning'%>
<% end %>
<br />
<p><%= link_to "Return to lists", lists_path, :class => 'btn btn-info'%></p>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<h4><%= @task.description %></h4>

<%= render 'form' %>

app/views/tasks/new.html.erb
<h1><%= @list.name %></h1>

<%= render 'form' %>